############################################################################
# Out-of-tree applications, linked into the NuttX apps tree as
# apps/external.
############################################################################

MENUDESC = "External Applications"

include $(APPDIR)/Directory.mk
